### PR TITLE
Fix unindention

### LINKED ISSUE #131: tikzDevice glitch
https://github.com/yihui/tikzDevice/commit/6e8cef0e6ecbadc698c4625f763805965b343198##commitcomment-23693950

### PR DESCRIPTION
**Pull request by lorenzwalthert**
This fixes #131. The problem is that it is not really really fixing it because of the interaction with the rule `update_indention_ref_fun_call()` (the first argument of `switch` in the example is right after `(`). `update_indention_ref_fun_call `  is implemented currently but should not really be part of `style_tidyverse()`. Hence, we have to drop the rule and adapt the tests first. I opened #134 for that.

### CODE REVIEW

File: tests/testthat/unindention/unindent_multi_line-in.R [hunk 1]
```diff
@@ -0,0 +1,10 @@
+call(
+  engine,
+  xetex = {
+         x
+       },
+       luatex= {
+       x
+       },{
+   xx
+  } )
```
Comment (krlmlr) [inline tests/testthat/unindention/unindent_multi_line-in.R]: Do you want to add a `FIXME` with a reference here?

Comment (lorenzwalthert) [inline tests/testthat/unindention/unindent_multi_line-in.R]: `FIXME` to leave a line blank after `}`you mean?

Comment (krlmlr) [inline tests/testthat/unindention/unindent_multi_line-in.R]: Yes.
