### PR TITLE
Reject styling wrongly parsed coder

### LINKED ISSUE #847: {styler} changes unicode characters on Windows
Example:

``` r
styler::style_text('suit <- "♠"')
#> suit <- "<U+2660>"
```

<sup>Created on 2021-10-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.1.1 (2021-08-10)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United Kingdom.1252 
#>  ctype    English_United Kingdom.1252 
#>  tz       Europe/Berlin               
#>  date     2021-10-04                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source        
#>  backports     1.2.1   2020-12-09 [1] CRAN (R 4.1.0)
#>  cli           3.0.1   2021-07-17 [1] CRAN (R 4.1.0)
#>  crayon        1.4.1   2021-02-08 [1] CRAN (R 4.1.1)
#>  digest        0.6.28  2021-09-23 [1] CRAN (R 4.1.1)
#>  ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.1.0)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.1.1)
#>  fansi         0.5.0   2021-05-25 [1] CRAN (R 4.1.1)
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.1.1)
#>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.1.1)
#>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.1.1)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.1.1)
#>  htmltools     0.5.2   2021-08-25 [1] CRAN (R 4.1.1)
#>  knitr         1.36    2021-09-29 [1] CRAN (R 4.1.1)
#>  lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.1.1)
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.1.1)
#>  pillar        1.6.3   2021-09-26 [1] CRAN (R 4.1.1)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.1.1)
#>  prettycode    1.1.0   2019-12-16 [1] CRAN (R 4.1.1)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.1.1)
#>  R.cache       0.15.0  2021-04-30 [1] CRAN (R 4.1.1)
#>  R.methodsS3   1.8.1   2020-08-26 [1] CRAN (R 4.1.0)
#>  R.oo          1.24.0  2020-08-26 [1] CRAN (R 4.1.0)
#>  R.utils       2.11.0  2021-09-26 [1] CRAN (R 4.1.1)
#>  reprex        2.0.1   2021-08-05 [1] CRAN (R 4.1.1)
#>  rlang         0.4.11  2021-04-30 [1] CRAN (R 4.1.1)
#>  rmarkdown     2.11    2021-09-14 [1] CRAN (R 4.1.1)
#>  rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.1.1)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.1.1)
#>  stringi       1.7.5   2021-10-04 [1] CRAN (R 4.1.1)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.1.1)
#>  styler        1.6.2   2021-09-23 [1] CRAN (R 4.1.1)
#>  tibble        3.1.5   2021-09-30 [1] CRAN (R 4.1.1)
#>  utf8          1.2.2   2021-07-24 [1] CRAN (R 4.1.1)
#>  vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.1.1)
#>  withr         2.4.2   2021-04-18 [1] CRAN (R 4.1.1)
#>  xfun          0.26    2021-09-14 [1] CRAN (R 4.1.1)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.1.0)
#> 
#> [1] C:/Users/IndrajeetPatil/Documents/R/win-library/4.1
#> [2] C:/Program Files/R/R-4.1.1/library
```

</details>

I am working in `.Rproject` with `UTF-8` text encoding:

image

And I also checked that

```r
> Encoding("♠")
[1] "UTF-8"
```

Based on https://github.com/r-lib/styler/issues/376, I thought this might be unexpected behavior?

### PR DESCRIPTION
**Pull request by lorenzwalthert**
Closes #847. Turns out we can't fix the problem because we can't construct a string like `"\U2660"` from "\U" and 2660: Error: '\U' used without hex digits in character string starting ""\U"". So windows users have to wait for R 4.2. @IndrajeetPatil I added a test to make sure it errors under certain circumstances.

### CODE REVIEW

File: R/parse.R [hunk 1]
```diff
@@ -97,7 +97,18 @@ get_parse_data <- function(text, include_text = TRUE, ...) {
...
     utils::getParseData(parsed, includeText = include_text),
     .name_repair = "minimal"
-  ) %>%
+  )
+  if (getRversion() < "4.2") {
+    is_unicode_parsing_error <- grepl("^<U\\+[0-9]+>$", pd$text)
+    if (any(is_unicode_parsing_error)) {
+      rlang::abort(
+        "Can't parse input due to unicode restriction in base R. Please ",
+        "upgrade R to style this input. ",
```
Comment (IndrajeetPatil) [inline R/parse.R:106]: Maybe you can specify the exact version of R here that the user needs to upgrade to?

Comment (lorenzwalthert) [reply R/parse.R]: I adapted it.
